[pytest]
addopts = '-rP'
DJANGO_SETTINGS_MODULE=wheel_analyzer.settings
python_files = tests.py test_*.py *_test.py
env =
    ENVIRONMENT=TESTING
    DATABASE_URL=postgresql://app:app@postgres:5432/app

