# Generated by Django 5.1.4 on 2025-11-03 01:06

import json
import os

from django.conf import settings
from django.db import migrations


def populate_curated_stocks(apps, schema_editor):
    """Populate CuratedStock table from scanner/data/options.json"""
    CuratedStock = apps.get_model("scanner", "CuratedStock")

    # Define the path to the JSON file
    json_file_path = os.path.join(settings.BASE_DIR, "scanner", "data", "options.json")

    # Check if file exists (may not exist in test environment)
    if not os.path.exists(json_file_path):
        # Use hardcoded list for test environments or when file is deleted
        tickers = [
            "AAPL",
            "ADBE",
            "AMZN",
            "ANET",
            "ASML",
            "AVGO",
            "CRM",
            "CRWD",
            "DDOG",
            "DUOL",
            "GOOGL",
            "JPM",
            "MA",
            "META",
            "MSFT",
            "NFLX",
            "NOW",
            "NVDA",
            "PANW",
            "PLTR",
            "PYPL",
            "SHOP",
            "SPGI",
            "SPOT",
            "UBER",
            "V",
        ]
    else:
        # Read the JSON file
        with open(json_file_path, "r") as file:
            data = json.load(file)
        # Extract tickers from the "put" key
        tickers = data.get("put", [])

    # Create CuratedStock objects for each ticker
    curated_stocks = []
    for ticker in tickers:
        curated_stocks.append(
            CuratedStock(symbol=ticker, active=True, notes="Imported from options.json")
        )

    # Bulk create all curated stocks
    CuratedStock.objects.bulk_create(curated_stocks)


def reverse_populate(apps, schema_editor):
    """Remove all CuratedStock objects created by this migration"""
    CuratedStock = apps.get_model("scanner", "CuratedStock")
    CuratedStock.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("scanner", "0002_curatedstock"),
    ]

    operations = [
        migrations.RunPython(populate_curated_stocks, reverse_populate),
    ]
