# Generated by Django 5.1.4 on 2025-11-05 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scanner", "0003_populate_curated_stocks"),
    ]

    operations = [
        migrations.AddField(
            model_name="curatedstock",
            name="current_eps",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Current Earnings Per Share (fetched from Alpha Vantage)",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="curatedstock",
            name="desired_return",
            field=models.DecimalField(
                decimal_places=2,
                default=15.0,
                help_text="Desired annual return rate (%) - used as discount rate",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="curatedstock",
            name="eps_growth_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=10.0,
                help_text="Expected EPS growth rate (%)",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="curatedstock",
            name="eps_multiple",
            field=models.DecimalField(
                decimal_places=2,
                default=20.0,
                help_text="Multiple applied to terminal year EPS for terminal value",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="curatedstock",
            name="intrinsic_value",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Calculated fair value per share based on DCF model",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="curatedstock",
            name="last_calculation_date",
            field=models.DateTimeField(
                blank=True,
                help_text="When the intrinsic value was last calculated",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="curatedstock",
            name="projection_years",
            field=models.IntegerField(
                default=5, help_text="Number of years to project EPS growth"
            ),
        ),
    ]
