# Generated by Django 5.1.4 on 2025-11-06 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scanner", "0004_add_intrinsic_value_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="curatedstock",
            name="current_fcf_per_share",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Trailing twelve months Free Cash Flow per share",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="curatedstock",
            name="fcf_growth_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=10.0,
                help_text="Expected FCF growth rate (%)",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="curatedstock",
            name="fcf_multiple",
            field=models.DecimalField(
                decimal_places=2,
                default=20.0,
                help_text="Multiple applied to terminal year FCF for terminal value",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="curatedstock",
            name="intrinsic_value_fcf",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Calculated fair value per share based on FCF DCF model",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="curatedstock",
            name="preferred_valuation_method",
            field=models.CharField(
                choices=[("EPS", "EPS-based"), ("FCF", "FCF-based")],
                default="EPS",
                help_text="Preferred valuation method to display",
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="curatedstock",
            name="intrinsic_value",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Calculated fair value per share based on EPS DCF model",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="curatedstock",
            name="projection_years",
            field=models.IntegerField(
                default=5, help_text="Number of years to project growth"
            ),
        ),
    ]
