# Generated by Django 5.1.4 on 2025-11-12 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scanner", "0006_add_last_calculation_date_index"),
    ]

    operations = [
        migrations.CreateModel(
            name="ValuationHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "snapshot_date",
                    models.DateField(
                        db_index=True,
                        help_text="Quarter-end date when this snapshot was taken (Jan 1, Apr 1, Jul 1, Oct 1)",
                    ),
                ),
                (
                    "calculated_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when this snapshot was created (may differ from snapshot_date)",
                    ),
                ),
                (
                    "intrinsic_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Intrinsic value calculated using EPS DCF model",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "current_eps",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Trailing Twelve Months EPS at time of snapshot",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "eps_growth_rate",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="EPS growth rate assumption (%) used in calculation",
                        max_digits=5,
                    ),
                ),
                (
                    "eps_multiple",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Terminal value multiple applied to Year 5 EPS",
                        max_digits=5,
                    ),
                ),
                (
                    "intrinsic_value_fcf",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Intrinsic value calculated using FCF DCF model",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "current_fcf_per_share",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Trailing Twelve Months FCF per share at time of snapshot",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "fcf_growth_rate",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="FCF growth rate assumption (%) used in calculation",
                        max_digits=5,
                    ),
                ),
                (
                    "fcf_multiple",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Terminal value multiple applied to Year 5 FCF",
                        max_digits=5,
                    ),
                ),
                (
                    "desired_return",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Desired annual return rate (%) used as discount rate",
                        max_digits=5,
                    ),
                ),
                (
                    "projection_years",
                    models.IntegerField(
                        help_text="Number of years projected in DCF model"
                    ),
                ),
                (
                    "preferred_valuation_method",
                    models.CharField(
                        choices=[("EPS", "EPS-based"), ("FCF", "FCF-based")],
                        default="EPS",
                        help_text="Preferred valuation method at time of snapshot",
                        max_length=3,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Optional notes about this valuation snapshot (e.g., assumption changes)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Valuation History",
                "verbose_name_plural": "Valuation Histories",
                "ordering": ["-snapshot_date", "stock__symbol"],
            },
        ),
        migrations.RemoveIndex(
            model_name="curatedstock",
            name="scanner_curated_stock_calc_date_idx",
        ),
        migrations.AlterField(
            model_name="curatedstock",
            name="current_eps",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Trailing Twelve Months Earnings Per Share (EPS TTM) - sum of 4 most recent quarterly reportedEPS from Alpha Vantage EARNINGS endpoint",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="valuationhistory",
            name="stock",
            field=models.ForeignKey(
                help_text="The stock this valuation history belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="valuation_history",
                to="scanner.curatedstock",
            ),
        ),
        migrations.AddIndex(
            model_name="valuationhistory",
            index=models.Index(
                fields=["stock", "-snapshot_date"],
                name="scanner_val_stock_i_8f4c9a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="valuationhistory",
            index=models.Index(
                fields=["snapshot_date"], name="scanner_val_snapsho_301a61_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="valuationhistory",
            index=models.Index(
                fields=["stock", "snapshot_date"], name="scanner_val_stock_i_d7a5d3_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="valuationhistory",
            constraint=models.UniqueConstraint(
                fields=("stock", "snapshot_date"),
                name="unique_stock_snapshot_date",
                violation_error_message="A valuation snapshot already exists for this stock and date.",
            ),
        ),
    ]
