# Generated by Django 5.1.4 on 2025-11-13 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scanner", "0007_create_valuation_history"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SavedSearch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ticker",
                    models.CharField(
                        help_text="Stock ticker symbol (uppercase)", max_length=10
                    ),
                ),
                (
                    "option_type",
                    models.CharField(
                        choices=[("put", "Put Options"), ("call", "Call Options")],
                        help_text="Type of options to scan",
                        max_length=4,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Optional notes for categorization (e.g., 'earnings play')",
                        null=True,
                    ),
                ),
                (
                    "scan_count",
                    models.IntegerField(
                        default=0, help_text="Number of times quick scan was executed"
                    ),
                ),
                (
                    "last_scanned_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp of most recent scan execution",
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this search was saved"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, help_text="Soft delete flag"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who saved this search",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_searches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Saved Search",
                "verbose_name_plural": "Saved Searches",
                "db_table": "scanner_saved_search",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_deleted"],
                        name="scanner_sav_user_id_409743_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="scanner_sav_created_e5e872_idx"
                    ),
                    models.Index(
                        fields=["last_scanned_at"],
                        name="scanner_sav_last_sc_071646_idx",
                    ),
                    models.Index(
                        fields=["scan_count"], name="scanner_sav_scan_co_6761f8_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_deleted", False)),
                        fields=("user", "ticker", "option_type"),
                        name="unique_active_saved_search",
                    )
                ],
            },
        ),
    ]
