# Generated by Django 5.1.4 on 2025-11-14 15:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scanner", "0008_savedsearch"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserQuota",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "daily_limit",
                    models.IntegerField(
                        default=25, help_text="Maximum scans allowed per day"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When quota was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Last modification timestamp"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        help_text="User this quota applies to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quota",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Quota",
                "verbose_name_plural": "User Quotas",
                "db_table": "scanner_user_quota",
            },
        ),
        migrations.CreateModel(
            name="ScanUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scan_type",
                    models.CharField(
                        choices=[
                            ("curated", "Curated Scanner"),
                            ("individual", "Individual Search"),
                        ],
                        help_text="Type of scan operation",
                        max_length=20,
                    ),
                ),
                (
                    "ticker",
                    models.CharField(
                        blank=True,
                        help_text="Stock symbol (for individual scans only)",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the scan was executed"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who performed the scan",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scan_usage",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Scan Usage",
                "verbose_name_plural": "Scan Usage Records",
                "db_table": "scanner_scan_usage",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["user", "timestamp"],
                        name="scanner_sca_user_id_30eeb9_idx",
                    ),
                    models.Index(
                        fields=["timestamp"], name="scanner_sca_timesta_394de6_idx"
                    ),
                ],
            },
        ),
    ]
