# Generated by Django 5.1.4 on 2025-11-14 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scanner", "0009_userquota_scanusage"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScanStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("aborted", "Aborted"),
                        ],
                        default="pending",
                        help_text="Current status of the scan operation",
                        max_length=20,
                    ),
                ),
                (
                    "scan_type",
                    models.CharField(
                        choices=[
                            ("curated", "Curated Stocks"),
                            ("individual", "Individual Stock"),
                        ],
                        default="curated",
                        help_text="Type of scan being performed",
                        max_length=20,
                    ),
                ),
                (
                    "start_time",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the scan started"
                    ),
                ),
                (
                    "end_time",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the scan completed/failed",
                        null=True,
                    ),
                ),
                (
                    "result_count",
                    models.IntegerField(
                        blank=True, help_text="Number of results found", null=True
                    ),
                ),
                (
                    "tickers_scanned",
                    models.IntegerField(
                        default=0, help_text="Number of tickers scanned"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="Error message if scan failed"
                    ),
                ),
            ],
            options={
                "verbose_name": "Scan Status",
                "verbose_name_plural": "Scan Statuses",
                "db_table": "scanner_scan_status",
                "ordering": ["-start_time"],
                "indexes": [
                    models.Index(
                        fields=["-start_time"], name="scanner_sca_start_t_90554e_idx"
                    ),
                    models.Index(
                        fields=["status"], name="scanner_sca_status_f9bdb3_idx"
                    ),
                ],
            },
        ),
    ]
