# Generated by Django 5.1.4 on 2025-11-14 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scanner", "0010_scanstatus"),
    ]

    operations = [
        migrations.AddField(
            model_name="curatedstock",
            name="current_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Latest stock price from marketdata API",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="curatedstock",
            name="price_updated_at",
            field=models.DateTimeField(
                blank=True, help_text="Timestamp when price was last fetched", null=True
            ),
        ),
        migrations.AddIndex(
            model_name="curatedstock",
            index=models.Index(
                fields=["price_updated_at"], name="scanner_cur_price_u_d6eab3_idx"
            ),
        ),
    ]
