# Generated by Django 5.0.6 on 2024-06-17 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="premium",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="type",
            field=models.CharField(
                choices=[
                    ("put", "Put"),
                    ("call", "Call"),
                    ("roll", "Roll"),
                    ("buy", "Buy"),
                    ("sell", "Sell"),
                    ("btc", "Buy To Close"),
                ],
                max_length=7,
            ),
        ),
    ]
