# Generated by Django 5.0.6 on 2024-06-15 15:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="transaction",
            options={"ordering": ["-transaction_date"]},
        ),
    ]
