# Generated by Django 5.0.6 on 2024-11-27 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0002_alter_transaction_premium_alter_transaction_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="campaign",
            options={"ordering": ["stock", "account", "-start_date"]},
        ),
        migrations.AlterModelOptions(
            name="transaction",
            options={"ordering": ["transaction_date"]},
        ),
        migrations.AlterField(
            model_name="campaign",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tracker.account"
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="campaign",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tracker.campaign"
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="type",
            field=models.CharField(
                choices=[
                    ("put", "Put"),
                    ("call", "Call"),
                    ("roll", "Roll"),
                    ("buy", "Buy"),
                    ("sell", "Sell"),
                    ("btc", "Buy To Close"),
                    ("div", "Dividend"),
                ],
                max_length=7,
            ),
        ),
    ]
